#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '👷 Running checks...'

yarn run husky:check-types

# Check Prettier standards
yarn run husky:check-format ||
(
    echo '❌ Prettier Check Failed.';
    echo 'Running "yarn run husky:fix-format" to fix the issues.';
		yarn run husky:fix-format;
		false;  # Fail it here so the fix can get committed
)

# Check ESLint Standards
yarn run husky:check-lint ||
(
	echo '❌ ESLint Check Failed.'
	false; 
)

# Check tsconfig standards
yarn run husky:check-types ||
(
    echo '❌ Type Check Failed.'
    false;
)

yarn run build ||
(
    echo '❌ Build Failed.'
    false;
)

# If everything passes... Now we can commit
echo '✅ All checks passed!'
